spring.application.name=backend-for-front
#spring.datasource.url=jdbc:postgresql://localhost:5432/frontrecipes
#spring.datasource.username=admin
#spring.datasource.password=admin

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/frontrecipes}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#86400000 ms = 24 hours. For production shorter access tokens (15 min) + refresh tokens, keep simple for now.
#app.jwt.secret=change-me-to-a-very-long-random-string-at-least-256-bits-long-for-hs256-algorithm
#app.jwt.expiration=86400000

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION:86400000}

spring.web.locale=en
spring.web.locale-resolver=fixed

server.port=8080